export interface Question {
  question: string;
  options: string[];
  answer: number;
}

export interface QuizData {
  [courseId: string]: Question[];
}

export const quizData: QuizData = {

  course1: [
    {
      "question": "What is the primary difference between declarative and imperative knowledge?",
      "options": [
        "Declarative is factual ('knowing what'), while imperative is procedural ('knowing how').",
        "Declarative is used for coding, while imperative is only for natural languages.",
        "Declarative is instruction-based, while imperative is a statement of fact.",
        "Declarative is stored in memory, while imperative is processed by the CPU."
      ],
      "answer": 0
    },
    {
      "question": "Which of the following is an example of imperative knowledge?",
      "options": [
        "Knowing that 2 + 2 = 4",
        "Knowing that the sky is blue",
        "Knowing the steps to tie a shoelace",
        "Knowing the definition of an algorithm"
      ],
      "answer": 2
    },
    {
      "question": "An algorithm is defined by which three characteristics?",
      "options": [
        "Hardware, software, and firmware",
        "Sequence of steps, flow of control, and a stop condition",
        "Syntax, semantics, and static semantics",
        "Input, output, and storage"
      ],
      "answer": 1
    },
    {
      "question": "According to the lecture, what are the two main things computers do?",
      "options": [
        "Surf the web and play videos",
        "Execute commands and update hardware",
        "Perform simple operations and remember results",
        "Compile code and debug syntax errors"
      ],
      "answer": 2
    },
    {
      "question": "What defines a 'Fixed Program' machine?",
      "options": [
        "A machine that can run any software installed",
        "A machine built to perform only one specific task or set of algorithms",
        "A machine where programs are stored in high-speed memory",
        "A machine that uses Python as its primary language"
      ],
      "answer": 1
    },
    {
      "question": "In a 'Stored Program' computer, where are program instructions kept?",
      "options": [
        "Only in the CPU",
        "In the same internal memory as the data",
        "On an external hard drive only",
        "In the BIOS chip"
      ],
      "answer": 1
    },
    {
      "question": "Which aspect of a programming language refers to the basic operations a CPU can perform directly?",
      "options": [
        "Syntax",
        "Semantics",
        "Primitives",
        "Static Semantics"
      ],
      "answer": 2
    },
    {
      "question": "Which of the following is categorized as a 'Data Movement' primitive?",
      "options": [
        "Add",
        "Load",
        "AND",
        "Multiply"
      ],
      "answer": 1
    },
    {
      "question": "What is 'Syntax' in the context of programming?",
      "options": [
        "The meaning behind the code",
        "The speed at which code executes",
        "The rules defining how statements and expressions must be written",
        "The process of finding logic errors"
      ],
      "answer": 2
    },
    {
      "question": "Which error occurs when code follows syntax rules but has no valid meaning according to the language?",
      "options": [
        "Syntax Error",
        "Static Semantic Error",
        "Runtime Error",
        "Logic Error"
      ],
      "answer": 1
    },
    {
      "question": "In Python, what type of error is generated by the expression \"hi\" + 5?",
      "options": [
        "Syntax Error",
        "Static Semantic Error (Type Mismatch)",
        "Runtime Error (Division by zero)",
        "Logic Error"
      ],
      "answer": 1
    },
    {
      "question": "When does a 'Dynamic' or 'Runtime' error typically occur?",
      "options": [
        "While writing the code",
        "During compilation",
        "While the program is actually running",
        "Before the program is translated"
      ],
      "answer": 2
    },
    {
      "question": "Which of the following is a runtime error in Python?",
      "options": [
        "Missing a closing parenthesis",
        "Adding an integer to a string",
        "Division by zero (1 / 0)",
        "Writing a comment"
      ],
      "answer": 2
    },
    {
      "question": "What is the Python interpreter's role regarding 'commands'?",
      "options": [
        "It stores them as data files only",
        "It executes them in a shell",
        "It changes the physical structure of the computer",
        "It defines the hardware architecture"
      ],
      "answer": 1
    },
    {
      "question": "What determines what operations can be performed on an object in Python?",
      "options": [
        "The object's name",
        "The object's type",
        "The CPU speed",
        "The size of the memory"
      ],
      "answer": 1
    },
    {
      "question": "Which operator is used for exponentiation in Python?",
      "options": [
        "^",
        "*",
        "**",
        "%"
      ],
      "answer": 2
    },
    {
      "question": "What is the result of the Python operation 'concatenation'?",
      "options": [
        "Adding two numbers",
        "Joining two strings together",
        "Repeating a string",
        "Finding the remainder of a division"
      ],
      "answer": 1
    },
    {
      "question": "Which of the following is a Python Boolean value?",
      "options": [
        "\"True\"",
        "true",
        "True",
        "1"
      ],
      "answer": 2
    },
    {
      "question": "What kind of collection is a Python 'List'?",
      "options": [
        "An unordered set of characters",
        "A fixed-size hardware register",
        "An ordered collection of objects",
        "A mathematical formula"
      ],
      "answer": 2
    },
    {
      "question": "Which list operation is used to add an item to the end of a list?",
      "options": [
        ".remove()",
        ".add()",
        ".append()",
        ".insert()"
      ],
      "answer": 2
    },
    {
      "question": "What is the data type of the value 9.0 in Python?",
      "options": [
        "Integer",
        "Float",
        "String",
        "Boolean"
      ],
      "answer": 1
    },
    {
      "question": "What will be the data type of the result of 'float(123)'?",
      "options": [
        "Integer",
        "String",
        "Float",
        "List"
      ],
      "answer": 2
    },
    {
      "question": "What is the result of 'int(7.9)' in Python?",
      "options": [
        "8",
        "7.0",
        "7",
        "Error"
      ],
      "answer": 2
    },
    {
      "question": "Which logical operations are allowed on Boolean types?",
      "options": [
        "+, -, *",
        "and, or, not",
        "append, remove",
        "slicing and indexing"
      ],
      "answer": 1
    },
    {
      "question": "In the expression 'x = 10', 'x' is the ________ and '10' is the ________.",
      "options": [
        "Constant, Variable",
        "Operator, Operand",
        "Variable, Object",
        "Function, Parameter"
      ],
      "answer": 2
    }
  ],

  course2: [
    {
      "question": "Which class do strings belong to in Python?",
      "options": ["text", "char", "str", "string"],
      "answer": 2
    },
    {
      "question": "What is the key characteristic of Python strings regarding changeability?",
      "options": ["Mutable", "Immutable", "Dynamic", "Static"],
      "answer": 1
    },
    {
      "question": "Which of the following is NOT a valid way to create a string in Python?",
      "options": ["'Hello'", "\"Hello\"", "'''Hello'''", "[Hello]"],
      "answer": 3
    },
    {
      "question": "What happens if you try to assign a new value to a specific index of a string?",
      "options": ["It updates the character", "It creates a new string", "It results in a TypeError", "It results in a ValueError"],
      "answer": 2
    },
    {
      "question": "Which operator is used for string concatenation?",
      "options": ["*", "&", "+", "."],
      "answer": 2
    },
    {
      "question": "What is the result of the operation 'A' * 3?",
      "options": ["A3", "AAA", "A A A", "Error"],
      "answer": 1
    },
    {
      "question": "Which operator is used to check if a substring exists within a string?",
      "options": ["has", "exists", "in", "within"],
      "answer": 2
    },
    {
      "question": "Python uses what type of indexing for strings?",
      "options": ["One-based indexing", "Zero-based indexing", "Random indexing", "Dynamic indexing"],
      "answer": 1
    },
    {
      "question": "In the string s = 'PYTHON', what is the output of print(s[0])?",
      "options": ["P", "Y", "N", "0"],
      "answer": 0
    },
    {
      "question": "What does a negative index of -1 refer to in a Python string?",
      "options": ["The first character", "The second character", "The last character", "The second-to-last character"],
      "answer": 2
    },
    {
      "question": "Which index refers to the second-to-last character of a string?",
      "options": ["-1", "0", "-2", "1"],
      "answer": 2
    },
    {
      "question": "What is the correct way to 'change' a character in a string?",
      "options": ["s[index] = 'new'", "Modify the original object", "Create a new string", "Use the update() method"],
      "answer": 2
    },
    {
      "question": "Which type of quotes are useful for defining multi-line strings?",
      "options": ["Single quotes", "Double quotes", "Triple quotes", "Backticks"],
      "answer": 2
    },
    {
      "question": "What is the output of 'Hi' + 'There'?",
      "options": ["Hi There", "HiThere", "Hi+There", "Error"],
      "answer": 1
    },
    {
      "question": "If s = 'PYTHON', what is the output of print(s[-3])?",
      "options": ["T", "H", "O", "Y"],
      "answer": 1
    },
    {
      "question": "What is the standard syntax to access a character in a string variable 's' at a specific 'index'?",
      "options": ["s(index)", "s[index]", "s{index}", "s.index"],
      "answer": 1
    },
    {
      "question": "Which function is used to get user input in Python?",
      "options": ["print()", "input()", "read()", "scan()"],
      "answer": 1
    },
    {
      "question": "According to the lecture agenda, what does 'Branching' involve?",
      "options": ["Loops and iterations", "Conditionals (if/elif/else)", "File handling", "String methods"],
      "answer": 1
    },
    {
      "question": "Which of the following can a Python string contain?",
      "options": ["Letters only", "Numbers only", "Symbols and whitespace", "All of the above"],
      "answer": 3
    },
    {
      "question": "What error is raised when attempting to modify a string directly?",
      "options": ["ValueError", "IndexError", "TypeError", "AttributeError"],
      "answer": 2
    },
    {
      "question": "What is the output of 'a' in 'Cat'?",
      "options": ["True", "False", "None", "Error"],
      "answer": 0
    },
    {
      "question": "Triple quotes in Python can be defined using:",
      "options": ["'''...'''", "\"\"\"...\"\"\"", "Both A and B", "None of the above"],
      "answer": 2
    },
    {
      "question": "Negative indexing is particularly useful when:",
      "options": ["The string is very long", "The string length is unknown", "The string contains numbers", "The string is immutable"],
      "answer": 1
    },
    {
      "question": "In zero-based indexing, the second character is at which index?",
      "options": ["0", "1", "2", "-2"],
      "answer": 1
    },
    {
      "question": "Which part of the lecture covers 'Text Processing and Manipulation'?",
      "options": ["Part 1: Strings", "Part 2: Input/Output", "Part 3: Branching", "Part 4: File Handling"],
      "answer": 0
    }
  ],

  course3: [
    {
      "question": "What is the primary purpose of a computational loop?",
      "options": ["To store data permanently", "To repeat a block of code as long as a condition is met", "To define new variables", "To perform one-time calculations"],
      "answer": 1
    },
    {
      "question": "According to the notes, what is a key benefit of using loops for repetitive tasks?",
      "options": ["Increased hardware requirements", "Code reduction and reduced redundancy", "Increased manual coding errors", "Lower scalability"],
      "answer": 1
    },
    {
      "question": "How do loops manage the 'state' of an application?",
      "options": ["By deleting data structures", "By cycling through data structures like arrays or lists", "By preventing user input", "By stopping program execution"],
      "answer": 1
    },
    {
      "question": "Manual coding of repetitive steps is described as:",
      "options": ["Highly efficient", "Scalable", "Error-prone and unscalable", "Zero-performance logic"],
      "answer": 2
    },
    {
      "question": "Which phase of iteration involves setting the starting state?",
      "options": ["Termination Condition", "Increment", "Initialization", "Exit Logic"],
      "answer": 2
    },
    {
      "question": "A typical counter variable used in an initializer is shown as:",
      "options": ["float f = 1.0", "int i = 0", "string s = ''", "bool b = true"],
      "answer": 1
    },
    {
      "question": "What does correct initialization prevent?",
      "options": ["Program termination", "Undefined behavior", "High performance", "Code reduction"],
      "answer": 1
    },
    {
      "question": "Which phase involves a Boolean evaluation to check if a loop should continue?",
      "options": ["Initializers", "Termination Conditions", "Iteration Body", "Memory Management"],
      "answer": 1
    },
    {
      "question": "In exit logic, what happens if the condition evaluates to false?",
      "options": ["The loop repeats again", "The control flow exits the loop immediately", "The counter resets to zero", "The program crashes"],
      "answer": 1
    },
    {
      "question": "What is a 'Safety Net' used to prevent in loop design?",
      "options": ["Code reduction", "Infinite loops", "Data pointers", "Deterministic behavior"],
      "answer": 1
    },
    {
      "question": "Which loop is described as the most basic form of iteration?",
      "options": ["For loop", "Do-while loop", "While loop", "Switch case"],
      "answer": 2
    },
    {
      "question": "What type of logic does a while loop use?",
      "options": ["Exit-controlled logic", "Entry-controlled logic", "Post-condition logic", "Manual logic"],
      "answer": 1
    },
    {
      "question": "A while loop checks the condition:",
      "options": ["After entering the loop body", "Only once at the end", "Before entering the loop body", "Every other iteration"],
      "answer": 2
    },
    {
      "question": "Which loop is ideal when the number of iterations is unknown at the start?",
      "options": ["For loop", "While loop", "Initialization loop", "Sequence loop"],
      "answer": 1
    },
    {
      "question": "What is a common use case for a while loop according to the text?",
      "options": ["Menu systems", "Reading a file until the end is reached", "Fixed mathematical increments", "Known array lengths"],
      "answer": 1
    },
    {
      "question": "The for loop is characterized as:",
      "options": ["Indefinite iteration", "Definite iteration", "Exit-controlled", "Unstructured control"],
      "answer": 1
    },
    {
      "question": "What three elements does a for loop typically combine in one line?",
      "options": ["Condition, Print, Exit", "Initialization, Condition, and Increment", "Input, Logic, Output", "Start, Middle, End"],
      "answer": 1
    },
    {
      "question": "When is a for loop best used?",
      "options": ["When the number of iterations is unknown", "When the number of iterations is known in advance", "For handling menu systems", "When there is no termination condition"],
      "answer": 1
    },
    {
      "question": "Which loop variant is described as exit-controlled?",
      "options": ["While loop", "For loop", "Do-while loop", "If-else block"],
      "answer": 2
    },
    {
      "question": "How many times is the code block in a do-while loop guaranteed to execute?",
      "options": ["Zero times", "At least once", "Exactly ten times", "Until the user stops it"],
      "answer": 1
    },
    {
      "question": "The do-while loop is perfect for:",
      "options": ["Definite iteration", "Menu systems", "File reading", "Counter-based logic"],
      "answer": 1
    },
    {
      "question": "What is the logic flow of a do-while loop?",
      "options": ["Condition -> Body -> Exit", "Body -> Condition Check -> Repeat/Exit", "Initialization -> Condition -> Body", "Exit -> Body -> Condition"],
      "answer": 1
    },
    {
      "question": "The provided syntax example 'for (let i = 0; i < n; i++)' belongs to which loop?",
      "options": ["While", "Do-While", "For", "Initialization"],
      "answer": 2
    },
    {
      "question": "What is the main advantage of structured control in for loops?",
      "options": ["High readability", "Infinite execution", "Manual increments", "Unknown iterations"],
      "answer": 0
    },
    {
      "question": "Loops allow a single logic block to handle how many iterations with zero performance degradation in logic overhead?",
      "options": ["Only 100", "Exactly 1,000", "Billions", "A maximum of 1 million"],
      "answer": 2
    }
  ],

  course4: [
    {
      "question": "Traditional procedural programming primarily focuses on which of the following?",
      "options": ["Objects and data", "A sequence of actions", "Hierarchical classification", "Data hiding"],
      "answer": 1
    },
    {
      "question": "How does Object-Oriented Programming (OOP) organize software?",
      "options": ["Around functions and logic", "Around data or objects", "As a linear sequence of steps", "By avoiding data structures"],
      "answer": 1
    },
    {
      "question": "Which of the following represents the 'Paradigm Shift' from procedural to OOP?",
      "options": ["calculate(data) to data.calculate()", "data.calculate() to calculate(data)", "data to function", "blueprint to instance"],
      "answer": 0
    },
    {
      "question": "In OOP, what is referred to as the 'Blueprint'?",
      "options": ["The Object", "The Class", "The Method", "The Attribute"],
      "answer": 1
    },
    {
      "question": "When does a Class consume memory during runtime?",
      "options": ["As soon as it is defined", "Never", "Only when instantiated", "During the design phase"],
      "answer": 2
    },
    {
      "question": "What is defined as the 'physical manifestation' of a class in memory?",
      "options": ["The Blueprint", "The Interface", "The Object", "The Logical Template"],
      "answer": 2
    },
    {
      "question": "Which statement is true regarding an Object's state?",
      "options": ["All objects share the same state", "Each object maintains its own unique state", "Objects do not have state", "State is only defined in the class template"],
      "answer": 1
    },
    {
      "question": "According to the core philosophy of OOP, what is at its heart?",
      "options": ["Inheritance", "Polymorphism", "Abstraction", "Encapsulation"],
      "answer": 2
    },
    {
      "question": "Which pillar of OOP involves bundling data and methods into a single unit?",
      "options": ["Abstraction", "Inheritance", "Encapsulation", "Polymorphism"],
      "answer": 2
    },
    {
      "question": "What is a primary benefit of Encapsulation?",
      "options": ["Code reuse", "Method overriding", "Preventing accidental corruption of internal state", "Creating an 'is-a' relationship"],
      "answer": 2
    },
    {
      "question": "Which modifiers are commonly used to implement Encapsulation?",
      "options": ["public and static", "private and protected", "global and local", "final and abstract"],
      "answer": 1
    },
    {
      "question": "Abstraction focuses on _____ rather than _____.",
      "options": ["How; What", "What; How", "Data; Methods", "Objects; Classes"],
      "answer": 1
    },
    {
      "question": "The remote control example (using buttons without knowing internal circuitry) illustrates which concept?",
      "options": ["Inheritance", "Polymorphism", "Abstraction", "Encapsulation"],
      "answer": 2
    },
    {
      "question": "What does Inheritance allow a new class (subclass) to do?",
      "options": ["Hide its data from other classes", "Inherit attributes and methods from a superclass", "Change the interface of the parent class", "Act as a template for other objects"],
      "answer": 1
    },
    {
      "question": "Which relationship is created by Inheritance?",
      "options": ["'has-a' relationship", "'is-a' relationship", "'uses-a' relationship", "'contains-a' relationship"],
      "answer": 1
    },
    {
      "question": "Which pillar is most associated with 'Code Reuse' across modules?",
      "options": ["Abstraction", "Encapsulation", "Inheritance", "Polymorphism"],
      "answer": 2
    },
    {
      "question": "What does Inheritance enable for custom behavior in a subclass?",
      "options": ["Data hiding", "Method overriding", "Method overloading", "Internal circuitry"],
      "answer": 1
    },
    {
      "question": "What is the literal meaning of Polymorphism provided in the notes?",
      "options": ["Data Protection", "One Interface, Many Forms", "Logical Template", "Hierarchical Classification"],
      "answer": 1
    },
    {
      "question": "Polymorphism allows objects of different classes to be treated as:",
      "options": ["Private components", "Objects of a common superclass", "Independent blueprints", "Static instances"],
      "answer": 1
    },
    {
      "question": "Method Overloading is an example of which type of Polymorphism?",
      "options": ["Runtime", "Compile-time", "Dynamic", "Structural"],
      "answer": 1
    },
    {
      "question": "Method Overriding is an example of which type of Polymorphism?",
      "options": ["Compile-time", "Runtime", "Static", "Abstract"],
      "answer": 1
    },
    {
      "question": "What is the common use of polymorphism regarding parent and child classes?",
      "options": ["Using a child class reference to refer to a parent object", "Using a parent class reference to refer to a child class object", "Merging two classes into one", "Hiding the parent class from the child class"],
      "answer": 1
    },
    {
      "question": "Which concept allows for decoupled systems where components can be swapped without collapsing the architecture?",
      "options": ["Procedure-oriented design", "Abstraction and its core philosophy", "Manual coding", "Linear sequence"],
      "answer": 1
    },
    {
      "question": "What does the 'Class' represent in the 'Blueprint metaphor'?",
      "options": ["The physical house", "The architectural drawing", "The construction materials", "The residents of the house"],
      "answer": 1
    },
    {
      "question": "Which of the following is NOT one of the 'Four Pillars' of OOP mentioned in the lecture?",
      "options": ["Encapsulation", "Abstraction", "Inheritance", "Modularization"],
      "answer": 3
    }
  ],

 
};